FROM golang:1.23-alpine AS builder

COPY . /app
WORKDIR /app

RUN go mod download
RUN go build -o ./bin/pvz_grpc ./cmd/gRPC/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/bin/pvz_grpc .

RUN chmod +x pvz_grpc

CMD ["./pvz_grpc"]
